[package]
name = "md-serve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
markdown = "1.0.0-alpha.17"
tokio = { version = "1.37.0", features = ["full"] }

